# -*- coding: utf-8 -*-
"""Abquirir_Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IUtVmdrubwOTppjrlb3NeG1oJs0SnHU
"""

from google.colab import drive
import os
if not os.path.exists('/content/drive'):
  drive.mount('/content/drive')

import pandas as pd
file_path = '/content/drive/My Drive/Clase Industrial 4.0/Datos.xlsx'
df = pd.read_excel(file_path)
df

import matplotlib.pyplot as plt
import pandas as pd

# Reemplaza 'ruta/al/archivo.csv' con la ruta a tu archivo CSV
df = pd.read_excel('/content/drive/MyDrive/Clase Industrial 4.0/Datos.xlsx')

# Selecciona las columnas que quieres graficar
df.plot(x='Voltaje (V)', y='Corriente (A)')

plt.show()

import numpy as np
# Array unidimensional
array1d = np.array([1, 2, 3, 4])
# Array b i d im e n s i o n a l
array2d = np.array([[1, 2, 3], [4, 5, 6]])
print (array2d)